### PR TITLE
Close on launch, unless pressing Ctrl

### LINKED ISSUE #14: Make it easier to close the Overlay window
Currently, when I use the shortcut to bring up the Overlay and select a workspace to open, the overlay window stays there. To close it, I have to focus on the search bar and then press Esc:

Current Behavior

This makes it hard to close the window, and, in my example (which just opens the Calculator app), it hides the opened app, which makes me think the action didn't work.

Planner on AppCenter also has a shortcut + overlay flow, and it's easier to close it. It has both a "Cancel" button, and also gets closed when you click outside of the window:

Desired Behavior

I think this is a much more intuitive flow, specially if the overlay also closes if a Workspace is selected too. I understand this might be an issue if the user wants to open multiple Workspaces though.

### PR DESCRIPTION
**Pull request by Philip-Scott**
Close when launching an application, unless pressing Ctrl 

Could fix #14, but it also deserves a Close button imo :)

### CODE REVIEW

**Comment by DevAlien** [comment]
Hey @Philip-Scott I very much appreciate this PR, it is also a special day for me in general.

This is very good, but as you said the most common behaviour is to open a single workspace or item. One of the ideas was to have the auto quit always ON and if you want to open more you could use CTRL + CLICK or CTRL+ENTER, what do you think?

Having the options there is nice, but you can still do just one or the other.

**Comment by Philip-Scott** [comment]
You know, I actually have no idea how to query the current keyboard state. Catching the keyboard events is not an option though as they are only active when the window has focus, so if you were to open a window with pressing Ctrl, the quick launcher would loose focus and would not get updates during that time.

You can try what I'm talking about with the following code snippet on QuickLaunchWindow.vala 

```vala
        Object (application: Application.instance,
                height_request: 700,
                icon_name: "com.github.devalien.workspaces",
                resizable: true,
                title: _ ("Workspaces"),
                width_request: 500,
                events: Gdk.EventMask.KEY_PRESS_MASK | Gdk.EventMask.KEY_RELEASE_MASK
        );

        key_press_event.connect((event) => {
            stdout.printf(@"Key Pressed: $(event.hardware_keycode)\n");
            return false;
        });

        key_release_event.connect((event) => {
            stdout.printf(@"Key Released: $(event.hardware_keycode)\n");
            return false;
        });
```

Do you happen to know how to pool the keyboard state at any moment?

**Comment by DevAlien** [comment]
@Philip-Scott I think I figured it out
```
            key_press_event.connect ((event) => {
                uint state = event.state & Gtk.accelerator_get_default_mod_mask ();
                if (state == Gdk.ModifierType.CONTROL_MASK) {
                    stdout.printf ("ctrl si pressed");
                }
                stdout.printf (@"Key Pressed: $(event.hardware_keycode)\n");
                return false;
            });
```

Try this one out when you press a it tells you if there's CTRL pressed, no idea if I can do the same for click. It is possible with an event to get that, but the activate doesnt pass any Gdk.Event

**Comment by DevAlien** [comment]
Ok I figured it out.

I have tested it in line 79, on list_box.row_activated.connect

```
Gdk.ModifierType state;

            if (Gtk.get_current_event_state (out state)) {
                var s = state & get_modifier_mask (Gdk.ModifierIntent.MODIFY_SELECTION);
                if (s == Gdk.ModifierType.CONTROL_MASK) {
                    stdout.printf ("ctrl si pressed\n");
                }
            }
```
Like that we know if control is pressed while clicking. The problem now is to make the listrow pressable with "return" key if the ctrl is pressed doesnt work. (at the moment when pressing it goes to the searchbar, but even adding a clause for that it won't work)

**Comment by Philip-Scott** [comment]
Ahh get_current_event_state, maybe that will work :) I'll test it out after lunch and update the PR with it

**Comment by DevAlien** [comment]
Changing the key_press_event for Return to :
```
case Gdk.Key.Control_L:
            case Gdk.Key.Control_R:
                return false;
            case Gdk.Key.Return :
                bool has_selection = list_box.get_selected_rows ().length () > 0;
                if (has_selection) {
                    list_box.activate ();
                }

                return true;
```
Makes it work, if we add the stuff on the above.

I guess it is doable this way. Now we can decide which way we want to take, if your idea or simply implementing it with ctrl, which is a bit more versatile since you can choose always what to do.

**Comment by Philip-Scott** [comment]
Updated the branch, nice one on `Gtk.get_current_event_state` btw!

**Comment by DevAlien** [comment]
Seems perfect. I will test it tomorrow morning (4am here) and then merge it. Thanks ! I'm working on the workspaces icon/edit/delete etc

**Pull request merged**
